### ISSUE TITLE
Define the configuration of the database in a .env instead of passing them as a parameter of the constructor of the ConnectionFactory class.

### ISSUE THREAD

**Issue by faso-dev** [faso-dev/osc-orm#2]
For better flexibility, I suggest that the ConnectionFactory class take the configuration of the database in the .env

**Comment by tsommie** [comment]
Your package is not standalone...so in production it is going to live in the `vendor` directory...it is not best practice to require another file from its core, instead it should depended on it, that is what the constructor is there for. Read up on SOLID STATE PRINCIPLES.

**Comment by tsommie** [comment]
Plus it gives you the convinience of calling multiple ConnectionFactory with different configurations. One may connect to MySql while the other may connect to an Sqlite. That is the sole purpose of Solid State Principal.

**Comment by faso-dev** [comment]
Yes I know. But if the user needs the connection in several places, he is obliged to pass all the time the connection info?
I thought that for connection reasons, it's not cool.
Obviously give it the possibility to extend a super class that will have access to its .env file, so the main class just defines the connection rules and that's it.

**Comment by tsommie** [comment]
Database connection is often done once in an application, and if there is a need for multiple connection then this approach will make more sence.....depending on a file that is not living in your root directory will cause things to break for the users of your library.

**Comment by faso-dev** [comment]
> Plus it gives you the convinience of calling multiple ConnectionFactory with different configurations. One may connect to MySql while the other may connect to an Sqlite. That is the sole purpose of Solid State Principal.

Absolutely. But what do you think of the second option? Before I close.

**Comment by faso-dev** [comment]
> Database connection is often done once in an application, and if there is a need for multiple connection then this approach will make more sence.....depending on a file that is not living in your root directory will cause things to break for the users of your library.

Okay. Finaly you're for the connectionBaseFactory to give the abitlity of user to extend it an work with env file. The only concern with our current solution is that if one day for example, he decides to go into production, he will have to change everywhere or he called the ConnectionFactory to adapt the parameters of his connection.

**Comment by tsommie** [comment]
I don't ever see a scenerio where any application will make so many database calls. This method is far more flexible trust me....Read the Solid State Principle and maybe you will understand.

**Comment by faso-dev** [comment]
> I don't ever see a scenerio where any application will make so many database calls. This method is far more flexible trust me....Read the Solid State Principle and maybe you will understand.

Okay. Thanks
