### ISSUE TITLE
There should be one entry point for your query library.

### ISSUE THREAD

**Issue by nascentafrica** [faso-dev/osc-orm#3]
I think there should be one entry point for your library, users don't need to instanciate different classes for Insert, Update, Delete and Select. You should have one class that should call the individual query builders from within, e.g.:
```
DB::insert()

DB::select()

DB::update()
```

Then from inside the `DB` class will look like this:

```
class DB
{
    static public insert()
    {
        return new QueryInsertBuilder();
    }


    static public select()
    {
        return new SelectBuilder();
    }
}
```

This may not be how i will go about doing it but it just to give you an idea what am trying to say.

**Comment by faso-dev** [comment]
> I think there should be one entry point for your library, users don't need to instanciate different classes for Insert, Update, Delete and Select. You should have one class that should call the individual query builders from within, e.g.:
> 
> ```
> DB::insert()
> 
> DB::select()
> 
> DB::update()
> ```
> 
> Then from inside the `DB` class will look like this:
> 
> ```
> class DB
> {
>     static public insert()
>     {
>         return new QueryInsertBuilder();
>     }
> 
> 
>     static public select()
>     {
>         return new SelectBuilder();
>     }
> }
> ```
> 
> This may not be how i will go about doing it but it just to give you an idea what am trying to say.

I completely agree. What is the method that you you could have used?

**Comment by nascentafrica** [comment]
> > I think there should be one entry point for your library, users don't need to instanciate different classes for Insert, Update, Delete and Select. You should have one class that should call the individual query builders from within, e.g.:
> > ```
> > DB::insert()
> > 
> > DB::select()
> > 
> > DB::update()
> > ```
> > 
> > 
> > Then from inside the `DB` class will look like this:
> > ```
> > class DB
> > {
> >     static public insert()
> >     {
> >         return new QueryInsertBuilder();
> >     }
> > 
> > 
> >     static public select()
> >     {
> >         return new SelectBuilder();
> >     }
> > }
> > ```
> > 
> > 
> > This may not be how i will go about doing it but it just to give you an idea what am trying to say.
> 
> I completely agree. What is the method that you you could have used?

Something like:

```
class DB
{
    use \Concerns\QueryInsertBuilder, SelectBuilder;

    static public insert()
    {
        // Do something from the QueryInsertBuilder trait
    }


    static public select()
    {
        // Do something from the SelectBuilder trait.
    }
}
```

**Comment by faso-dev** [comment]
Okay. I'll do it in the next commit
